language: python
sudo: required
dist: xenial
cache:
    pip: true
    directories:
        - /tmp/languages
python:
    - '3.5'
    - '3.6'
    - '3.7'
    - 'nightly'
install:
    - pip install pipenv
    - travis_retry pipenv install --dev --system
    - make
before_script:
    - wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
    - sudo apt-get -f --allow-unauthenticated install apertium-all-dev
    - sudo apt-get -f --allow-unauthenticated install apertium-sme-nob apertium-es-en
    - git clone --depth 1 https://github.com/apertium/apertium-nno /tmp/languages/apertium-nno || echo 'Using cached apertium-nno'
    - ( cd /tmp/languages/apertium-nno && ./autogen.sh && make -j2 )
script:
    - NONPAIRS=/tmp/languages make test
after_success:
    - coveralls
notifications:
    irc:
        channels:
            - secure: 'Ijxnr2SbP1iqWO1puvWTQfyzW2yav/OCSScy6F20MOtBLozYEeHn6ruzLVPa7r7/FibCBkS6tCYQx9DJeJwJaXAn81VEY1Fk9B5SeiMpm5VWjN83YIeJzpEkiIT1YfEU5nfgYyOyqzaVJbE6Ssae/SBsfkYrYqd8T1YajoWO/qNX/0VfLBtfHSR2ysx/IbXM3McMnqBRS+WGHBijSOIewp7SCnAJ+J7SYLLkwFIdE1eFELiDBLv0ciiPacShGy4A3pNZyJDeI/CFgs+gNEZEwiG4gjuW1sdZ1NfvktCTmpzH185Co1YaGVpzCDSlp+IuKyKGjbQE+n2q66V1fixVq9rL15MibzZU/846YLPLYkHOM8ZTMXB4VLtyz2/JgAe0M78QM+1nKD3QqN2tPIHCTohvwrw7RGVNZHh4LMkbSLfeuyXBM/znlWmBCS14bFvNK+jrZdVm1m3ltIrMZpC+E90EQ/KAoSONeF8l/sW+Q92lI/2jGVOuQmSJrlNUIjKb3cCGZU03AVveNa7Y5bP/LfP64xBfApPgmdl7LVLmFJbNP+N+0M13bTUHOuxqV0OLxYM7M9VUPW4PwGCRc+OvgrHa7hHzSPKYZFZ9Yvt8KB2PTZojxrYn+2179mVj78NkuOEs980MpsbKRwpSLYhCL7tDHclyb6vQAJTOFagkXO0='
    on_failure: change
    on_success: change
matrix:
  allow_failures:
    - python: nightly

    # The irc channel is encrypted for apertium/apertium-apy, so build notifications from forks won't show up on the IRC channel
    # Encrypt with:
    # $ gem install --user-install travis
    # $ ~/.gem/ruby/*/bin/travis encrypt -r apertium/apertium-apy 'chat.freenode.net#apertium'
