language: python

python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.5-dev"
    - "nightly"

install: pip3 install --user tornado

before_script:
    - wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
    - sudo apt-get -f install apertium-all-dev
    - sudo apt-get -f install apertium-sme-nob apertium-es-en
    - svn co https://svn.code.sf.net/p/apertium/svn/languages/apertium-nno /tmp/languages/apertium-nno
    - cd /tmp/languages/apertium-nno && ./autogen.sh && make -j2

script:
    - NONPAIRS=/tmp/languages t/run-tests

